name: MSBuild

on: [push, workflow_dispatch]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: R136.sln

  # Configuration type to build.
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        platform: [x86, x64]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install PDCurses vcpkg
      working-directory: ${{env.VCPKG_INSTALLATION_ROOT}}
      run: vcpkg install pdcurses:${{ matrix.platform }}-windows

    - name: Enable vcpkg integration
      working-directory: ${{env.VCPKG_INSTALLATION_ROOT}}
      run: vcpkg integrate install

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{ matrix.platform }} ${{env.SOLUTION_FILE_PATH}}
